source 'https://rubygems.org'

gem "rspec"
gem "sequel"
gem "redis"
gem 'oj', :require=>"oj"
gem 'eventmachine_httpserver', :require => 'evma_httpserver'
gem 'eventmachine', :require=>"eventmachine"
gem 'em-http-request'
gem 'oj', :require=>"oj"